version : '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name : nginx
    ports:
      - "8088:80"
    volumes: 
      - ./src/app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports: 
      - "4306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - laravel

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - laravel

  redis:
    image: redis:4.0
    container_name: redis_40
    ports:
      - "8002:6379"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src/app:/var/www/html
    ports:
      - "9000:9000"    
    networks:
      - laravel

volumes:
  mysql: